import { Course, Student, Quiz, QuizAttempt, StudentPlan } from '../types';

export const mockCourses: Course[] = [
  {
    id: 'c1',
    moodle_course_id: 101,
    course_name: 'Introduction to Computer Science',
    short_name: 'CS101',
    created_at: new Date().toISOString(),
  },
  {
    id: 'c2',
    moodle_course_id: 102,
    course_name: 'Data Structures & Algorithms',
    short_name: 'CS201',
    created_at: new Date().toISOString(),
  },
];

export const mockStudents: Student[] = [
  {
    id: 's1',
    moodle_user_id: 201,
    email: 'alex.smith@university.edu',
    full_name: 'Alex Smith',
    department: 'Computer Science',
    created_at: new Date().toISOString(),
  },
  {
    id: 's2',
    moodle_user_id: 202,
    email: 'maria.garcia@university.edu',
    full_name: 'Maria Garcia',
    department: 'Computer Science',
    created_at: new Date().toISOString(),
  },
  {
    id: 's3',
    moodle_user_id: 203,
    email: 'sam.wilson@university.edu',
    full_name: 'Sam Wilson',
    department: 'Software Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's4',
    moodle_user_id: 204,
    email: 'elena.rostova@university.edu',
    full_name: 'Elena Rostova',
    department: 'Data Science',
    created_at: new Date().toISOString(),
  },
  {
    id: 's5',
    moodle_user_id: 205,
    email: 'david.chen@university.edu',
    full_name: 'David Chen',
    department: 'Information Tech',
    created_at: new Date().toISOString(),
  },
];

export const mockQuizzes: Quiz[] = [
  {
    id: 'q1',
    moodle_quiz_id: 301,
    course_id: 'c1',
    quiz_name: 'Module 1: Variables & Control Flow',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: 'q2',
    moodle_quiz_id: 302,
    course_id: 'c1',
    quiz_name: 'Module 2: Functions & Recursion',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: 'q3',
    moodle_quiz_id: 303,
    course_id: 'c2',
    quiz_name: 'Midterm: Trees & Graph Traversal',
    max_score: 100,
    passing_score: 50,
    created_at: new Date().toISOString(),
  },
];

export const mockAttempts: QuizAttempt[] = [
  // Module 1 Quiz Attempts
  {
    id: 'a1',
    moodle_attempt_id: 4001,
    student_id: 's1',
    quiz_id: 'q1',
    attempt_number: 1,
    score_obtained: 88,
    max_score: 100,
    percentage: 88,
    status: 'passed',
    time_taken_seconds: 1420,
    submitted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'a2',
    moodle_attempt_id: 4002,
    student_id: 's2',
    quiz_id: 'q1',
    attempt_number: 1,
    score_obtained: 95,
    max_score: 100,
    percentage: 95,
    status: 'passed',
    time_taken_seconds: 1100,
    submitted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'a3',
    moodle_attempt_id: 4003,
    student_id: 's3',
    quiz_id: 'q1',
    attempt_number: 1,
    score_obtained: 42,
    max_score: 100,
    percentage: 42,
    status: 'failed',
    time_taken_seconds: 2100,
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'a4',
    moodle_attempt_id: 4004,
    student_id: 's4',
    quiz_id: 'q1',
    attempt_number: 1,
    score_obtained: 74,
    max_score: 100,
    percentage: 74,
    status: 'passed',
    time_taken_seconds: 1650,
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'a5',
    moodle_attempt_id: 4005,
    student_id: 's5',
    quiz_id: 'q1',
    attempt_number: 1,
    score_obtained: 52,
    max_score: 100,
    percentage: 52,
    status: 'failed',
    time_taken_seconds: 1890,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  // Module 2 Quiz Attempts
  {
    id: 'a6',
    moodle_attempt_id: 4006,
    student_id: 's1',
    quiz_id: 'q2',
    attempt_number: 1,
    score_obtained: 82,
    max_score: 100,
    percentage: 82,
    status: 'passed',
    time_taken_seconds: 1510,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a7',
    moodle_attempt_id: 4007,
    student_id: 's2',
    quiz_id: 'q2',
    attempt_number: 1,
    score_obtained: 98,
    max_score: 100,
    percentage: 98,
    status: 'passed',
    time_taken_seconds: 980,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a8',
    moodle_attempt_id: 4008,
    student_id: 's3',
    quiz_id: 'q2',
    attempt_number: 1,
    score_obtained: 38,
    max_score: 100,
    percentage: 38,
    status: 'failed',
    time_taken_seconds: 2300,
    submitted_at: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'a9',
    moodle_attempt_id: 4009,
    student_id: 's4',
    quiz_id: 'q2',
    attempt_number: 1,
    score_obtained: 80,
    max_score: 100,
    percentage: 80,
    status: 'passed',
    time_taken_seconds: 1400,
    submitted_at: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: 'a10',
    moodle_attempt_id: 4010,
    student_id: 's5',
    quiz_id: 'q2',
    attempt_number: 1,
    score_obtained: 64,
    max_score: 100,
    percentage: 64,
    status: 'passed',
    time_taken_seconds: 1700,
    submitted_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
];

export const mockPlans: StudentPlan[] = [
  {
    id: 'p1',
    student_id: 's3',
    risk_level: 'high',
    status: 'active',
    target_goal: 'Reach 65% in Quiz 3 (Data Structures)',
    action_plan: 'Schedule 1-on-1 tutoring on recursion & control flow logic. Assign 3 practice exercises before Quiz 3.',
    notes: 'Struggled with multi-branch recursion conditions in Quiz 2.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'p2',
    student_id: 's5',
    risk_level: 'medium',
    status: 'in_progress',
    target_goal: 'Improve average score to >75%',
    action_plan: 'Provide supplementary video lectures on loop invariants.',
    notes: 'Showed progress from Quiz 1 (52%) to Quiz 2 (64%).',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'p3',
    student_id: 's2',
    risk_level: 'excelling',
    status: 'monitoring',
    target_goal: 'Advanced project challenge',
    action_plan: 'Offer peer-mentoring role or advanced bonus algorithms challenge.',
    notes: 'Consistently top performer (>95%).',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];
