import { Institute, Course, Student, Quiz, QuizAttempt, StudentPlan } from '../types';

export const mockInstitutes: Institute[] = [
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    name: 'Pitthugram LMS (cx001)',
    code: 'CX001_PITTHU',
    city: 'Delhi NCR',
    moodle_url: 'https://cx001.pitthugram.com',
    created_at: new Date().toISOString(),
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'Pitthugram Super 30 Academy',
    code: 'PITTHU_S30',
    city: 'Noida',
    moodle_url: 'https://lms.pitthugram.com',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Apex Coaching Classes',
    code: 'APEX_KOTA',
    city: 'Kota',
    moodle_url: 'https://moodle.apexclasses.in',
    created_at: new Date().toISOString(),
  },
];

export const mockCourses: Course[] = [
  {
    id: 'c1',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_course_id: 1001,
    course_name: 'Class 12 Advanced JEE Physics',
    short_name: 'JEE-PHY-12',
    class_name: 'Class 12 - JEE Advanced',
    created_at: new Date().toISOString(),
  },
  {
    id: 'c2',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_course_id: 1002,
    course_name: 'Class 12 Mathematics & Calculus',
    short_name: 'JEE-MATH-12',
    class_name: 'Class 12 - JEE Advanced',
    created_at: new Date().toISOString(),
  },
  {
    id: 'c3',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_course_id: 1003,
    course_name: 'Class 11 NEET Droppers Physics',
    short_name: 'NEET-PHY-11',
    class_name: 'Class 11 - NEET Droppers',
    created_at: new Date().toISOString(),
  },
  {
    id: 'c4',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_course_id: 1004,
    course_name: 'Class 10 Foundation Math & Science',
    short_name: 'C10-FOUND',
    class_name: 'Class 10 - Foundation',
    created_at: new Date().toISOString(),
  },
];

export const mockStudents: Student[] = [
  {
    id: 's1',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2001,
    email: 'alex.smith@pitthugram.com',
    full_name: 'Alex Smith',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-001',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's2',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2002,
    email: 'maria.garcia@pitthugram.com',
    full_name: 'Maria Garcia',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-002',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's3',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2003,
    email: 'sam.wilson@pitthugram.com',
    full_name: 'Sam Wilson',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-003',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's4',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2004,
    email: 'elena.rostova@pitthugram.com',
    full_name: 'Elena Rostova',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-004',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's5',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2005,
    email: 'david.chen@pitthugram.com',
    full_name: 'David Chen',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-005',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's6',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2006,
    email: 'rahul.sharma@pitthugram.com',
    full_name: 'Rahul Sharma',
    class_name: 'Class 11 - NEET Droppers',
    roll_no: 'APX-101',
    department: 'Medical',
    created_at: new Date().toISOString(),
  },
  {
    id: 's7',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2007,
    email: 'priya.verma@pitthugram.com',
    full_name: 'Priya Verma',
    class_name: 'Class 11 - NEET Droppers',
    roll_no: 'APX-102',
    department: 'Medical',
    created_at: new Date().toISOString(),
  },
  {
    id: 's8',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2008,
    email: 'ananya.singh@pitthugram.com',
    full_name: 'Ananya Singh',
    class_name: 'Class 10 - Foundation',
    roll_no: 'APX-201',
    department: 'Foundation',
    created_at: new Date().toISOString(),
  },
  {
    id: 's9',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_user_id: 2009,
    email: 'vikram.aditya@pitthugram.com',
    full_name: 'Vikram Aditya',
    class_name: 'Class 10 - Foundation',
    roll_no: 'APX-202',
    department: 'Foundation',
    created_at: new Date().toISOString(),
  },
];

export const mockQuizzes: Quiz[] = [
  {
    id: 'q1',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_quiz_id: 3001,
    course_id: 'c1',
    quiz_name: 'JEE Physics: Rotational Dynamics',
    class_name: 'Class 12 - JEE Advanced',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: 'q2',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_quiz_id: 3002,
    course_id: 'c2',
    quiz_name: 'JEE Maths: Definite Integration',
    class_name: 'Class 12 - JEE Advanced',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: 'q3',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_quiz_id: 3003,
    course_id: 'c3',
    quiz_name: 'NEET Assessment 1: Newton Laws',
    class_name: 'Class 11 - NEET Droppers',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: 'q4',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_quiz_id: 3004,
    course_id: 'c4',
    quiz_name: 'Class 10 Term 1: Quadratic Equations',
    class_name: 'Class 10 - Foundation',
    max_score: 100,
    passing_score: 50,
    created_at: new Date().toISOString(),
  },
];

export const mockAttempts: QuizAttempt[] = [
  {
    id: 'a1',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6001,
    student_id: 's1',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 88,
    max_score: 100,
    percentage: 88,
    status: 'passed',
    time_taken_seconds: 1420,
    submitted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'a2',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6002,
    student_id: 's2',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 95,
    max_score: 100,
    percentage: 95,
    status: 'passed',
    time_taken_seconds: 1100,
    submitted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'a3',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6003,
    student_id: 's3',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 42,
    max_score: 100,
    percentage: 42,
    status: 'failed',
    time_taken_seconds: 2100,
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'a4',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6004,
    student_id: 's4',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 74,
    max_score: 100,
    percentage: 74,
    status: 'passed',
    time_taken_seconds: 1650,
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'a5',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6005,
    student_id: 's5',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 52,
    max_score: 100,
    percentage: 52,
    status: 'failed',
    time_taken_seconds: 1890,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a6',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6006,
    student_id: 's1',
    quiz_id: 'q2',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 82,
    max_score: 100,
    percentage: 82,
    status: 'passed',
    time_taken_seconds: 1510,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a7',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6007,
    student_id: 's2',
    quiz_id: 'q2',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 98,
    max_score: 100,
    percentage: 98,
    status: 'passed',
    time_taken_seconds: 980,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a8',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6008,
    student_id: 's3',
    quiz_id: 'q2',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 38,
    max_score: 100,
    percentage: 38,
    status: 'failed',
    time_taken_seconds: 2300,
    submitted_at: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'a9',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6009,
    student_id: 's6',
    quiz_id: 'q3',
    class_name: 'Class 11 - NEET Droppers',
    attempt_number: 1,
    score_obtained: 92,
    max_score: 100,
    percentage: 92,
    status: 'passed',
    time_taken_seconds: 1800,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a10',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6010,
    student_id: 's7',
    quiz_id: 'q3',
    class_name: 'Class 11 - NEET Droppers',
    attempt_number: 1,
    score_obtained: 46,
    max_score: 100,
    percentage: 46,
    status: 'failed',
    time_taken_seconds: 2400,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a11',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6011,
    student_id: 's8',
    quiz_id: 'q4',
    class_name: 'Class 10 - Foundation',
    attempt_number: 1,
    score_obtained: 88,
    max_score: 100,
    percentage: 88,
    status: 'passed',
    time_taken_seconds: 1500,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a12',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    moodle_attempt_id: 6012,
    student_id: 's9',
    quiz_id: 'q4',
    class_name: 'Class 10 - Foundation',
    attempt_number: 1,
    score_obtained: 78,
    max_score: 100,
    percentage: 78,
    status: 'passed',
    time_taken_seconds: 1600,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const mockPlans: StudentPlan[] = [
  {
    id: 'p1',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    student_id: 's3',
    risk_level: 'high',
    status: 'active',
    target_goal: 'Reach 65% in JEE Physics Quiz 3',
    action_plan: 'Schedule 1-on-1 tutoring on rotational dynamics and moments of inertia.',
    notes: 'Struggled with torque calculations.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'p2',
    institute_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    student_id: 's7',
    risk_level: 'high',
    status: 'active',
    target_goal: 'Improve score to >70% in NEET Physics',
    action_plan: 'Provide supplementary video lectures on friction and free-body diagrams.',
    notes: 'Needs extra practice on inclined plane vectors.',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
