import { Institute, Course, Student, Quiz, QuizAttempt, StudentPlan } from '../types';

export const mockInstitutes: Institute[] = [
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'Pitthugram Super 30 Institute',
    code: 'PITTHU_S30',
    city: 'Noida',
    moodle_url: 'https://lms.pitthugram.com',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Apex Coaching Classes',
    code: 'APEX_KOTA',
    city: 'Kota',
    moodle_url: 'https://moodle.apexclasses.in',
    created_at: new Date().toISOString(),
  },
];

export const mockCourses: Course[] = [
  // Institute 1: Pitthugram
  {
    id: 'c1',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_course_id: 101,
    course_name: 'JEE Physics & Advanced Mechanics',
    short_name: 'JEE-PHY',
    class_name: 'Class 12 - JEE Advanced',
    created_at: new Date().toISOString(),
  },
  {
    id: 'c2',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_course_id: 102,
    course_name: 'JEE Mathematics & Calculus',
    short_name: 'JEE-MATH',
    class_name: 'Class 12 - JEE Advanced',
    created_at: new Date().toISOString(),
  },
  // Institute 2: Apex Coaching
  {
    id: 'c3',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_course_id: 501,
    course_name: 'NEET Physics: Mechanics & Optics',
    short_name: 'NEET-PHY',
    class_name: 'Class 11 - NEET Droppers',
    created_at: new Date().toISOString(),
  },
  {
    id: 'c4',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_course_id: 502,
    course_name: 'Class 10 Science & Mathematics',
    short_name: 'C10-FOUND',
    class_name: 'Class 10 - Foundation',
    created_at: new Date().toISOString(),
  },
];

export const mockStudents: Student[] = [
  // Pitthugram Students
  {
    id: 's1',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_user_id: 201,
    email: 'alex.smith@pitthugram.edu',
    full_name: 'Alex Smith',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-001',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's2',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_user_id: 202,
    email: 'maria.garcia@pitthugram.edu',
    full_name: 'Maria Garcia',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-002',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's3',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_user_id: 203,
    email: 'sam.wilson@pitthugram.edu',
    full_name: 'Sam Wilson',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-003',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's4',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_user_id: 204,
    email: 'elena.rostova@pitthugram.edu',
    full_name: 'Elena Rostova',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-004',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  {
    id: 's5',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_user_id: 205,
    email: 'david.chen@pitthugram.edu',
    full_name: 'David Chen',
    class_name: 'Class 12 - JEE Advanced',
    roll_no: 'JEE-005',
    department: 'Engineering',
    created_at: new Date().toISOString(),
  },
  // Apex Coaching Students
  {
    id: 's6',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_user_id: 601,
    email: 'rahul.sharma@apex.in',
    full_name: 'Rahul Sharma',
    class_name: 'Class 11 - NEET Droppers',
    roll_no: 'APX-101',
    department: 'Medical',
    created_at: new Date().toISOString(),
  },
  {
    id: 's7',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_user_id: 602,
    email: 'priya.verma@apex.in',
    full_name: 'Priya Verma',
    class_name: 'Class 11 - NEET Droppers',
    roll_no: 'APX-102',
    department: 'Medical',
    created_at: new Date().toISOString(),
  },
  {
    id: 's8',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_user_id: 603,
    email: 'ananya.singh@apex.in',
    full_name: 'Ananya Singh',
    class_name: 'Class 10 - Foundation',
    roll_no: 'APX-201',
    department: 'Foundation',
    created_at: new Date().toISOString(),
  },
  {
    id: 's9',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_user_id: 604,
    email: 'vikram.aditya@apex.in',
    full_name: 'Vikram Aditya',
    class_name: 'Class 10 - Foundation',
    roll_no: 'APX-202',
    department: 'Foundation',
    created_at: new Date().toISOString(),
  },
];

export const mockQuizzes: Quiz[] = [
  // Pitthugram Quizzes
  {
    id: 'q1',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_quiz_id: 301,
    course_id: 'c1',
    quiz_name: 'JEE Physics: Rotational Dynamics',
    class_name: 'Class 12 - JEE Advanced',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: 'q2',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_quiz_id: 302,
    course_id: 'c2',
    quiz_name: 'JEE Maths: Definite Integration',
    class_name: 'Class 12 - JEE Advanced',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  // Apex Quizzes
  {
    id: 'q3',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_quiz_id: 701,
    course_id: 'c3',
    quiz_name: 'NEET Assessment 1: Newton Laws',
    class_name: 'Class 11 - NEET Droppers',
    max_score: 100,
    passing_score: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: 'q4',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_quiz_id: 702,
    course_id: 'c4',
    quiz_name: 'Class 10 Term 1: Quadratic Equations',
    class_name: 'Class 10 - Foundation',
    max_score: 100,
    passing_score: 50,
    created_at: new Date().toISOString(),
  },
];

export const mockAttempts: QuizAttempt[] = [
  // Pitthugram Attempts
  {
    id: 'a1',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4001,
    student_id: 's1',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 88,
    max_score: 100,
    percentage: 88,
    status: 'passed',
    time_taken_seconds: 1420,
    submitted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'a2',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4002,
    student_id: 's2',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 95,
    max_score: 100,
    percentage: 95,
    status: 'passed',
    time_taken_seconds: 1100,
    submitted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'a3',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4003,
    student_id: 's3',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 42,
    max_score: 100,
    percentage: 42,
    status: 'failed',
    time_taken_seconds: 2100,
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'a4',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4004,
    student_id: 's4',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 74,
    max_score: 100,
    percentage: 74,
    status: 'passed',
    time_taken_seconds: 1650,
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'a5',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4005,
    student_id: 's5',
    quiz_id: 'q1',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 52,
    max_score: 100,
    percentage: 52,
    status: 'failed',
    time_taken_seconds: 1890,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a6',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4006,
    student_id: 's1',
    quiz_id: 'q2',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 82,
    max_score: 100,
    percentage: 82,
    status: 'passed',
    time_taken_seconds: 1510,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a7',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4007,
    student_id: 's2',
    quiz_id: 'q2',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 98,
    max_score: 100,
    percentage: 98,
    status: 'passed',
    time_taken_seconds: 980,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a8',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    moodle_attempt_id: 4008,
    student_id: 's3',
    quiz_id: 'q2',
    class_name: 'Class 12 - JEE Advanced',
    attempt_number: 1,
    score_obtained: 38,
    max_score: 100,
    percentage: 38,
    status: 'failed',
    time_taken_seconds: 2300,
    submitted_at: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  // Apex Attempts
  {
    id: 'a9',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_attempt_id: 5001,
    student_id: 's6',
    quiz_id: 'q3',
    class_name: 'Class 11 - NEET Droppers',
    attempt_number: 1,
    score_obtained: 92,
    max_score: 100,
    percentage: 92,
    status: 'passed',
    time_taken_seconds: 1800,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a10',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_attempt_id: 5002,
    student_id: 's7',
    quiz_id: 'q3',
    class_name: 'Class 11 - NEET Droppers',
    attempt_number: 1,
    score_obtained: 46,
    max_score: 100,
    percentage: 46,
    status: 'failed',
    time_taken_seconds: 2400,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a11',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_attempt_id: 5003,
    student_id: 's8',
    quiz_id: 'q4',
    class_name: 'Class 10 - Foundation',
    attempt_number: 1,
    score_obtained: 88,
    max_score: 100,
    percentage: 88,
    status: 'passed',
    time_taken_seconds: 1500,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'a12',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    moodle_attempt_id: 5004,
    student_id: 's9',
    quiz_id: 'q4',
    class_name: 'Class 10 - Foundation',
    attempt_number: 1,
    score_obtained: 78,
    max_score: 100,
    percentage: 78,
    status: 'passed',
    time_taken_seconds: 1600,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const mockPlans: StudentPlan[] = [
  {
    id: 'p1',
    institute_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    student_id: 's3',
    risk_level: 'high',
    status: 'active',
    target_goal: 'Reach 65% in JEE Physics Quiz 3',
    action_plan: 'Schedule 1-on-1 tutoring on rotational dynamics and moments of inertia.',
    notes: 'Struggled with torque calculations.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'p2',
    institute_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    student_id: 's7',
    risk_level: 'high',
    status: 'active',
    target_goal: 'Improve score to >70% in NEET Physics',
    action_plan: 'Provide supplementary video lectures on friction and free-body diagrams.',
    notes: 'Needs extra practice on inclined plane vectors.',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
